version: '3'

services:
  backend:
    container_name: backend_openai
    build:
      context: .
    ports:
      - '${APPLICATION_PORT:-3000}:3000'
    volumes:
      - type: bind
        source: ./temp
        target: /usr/src/static
    depends_on:
      - postgres_openai
      - redis
    restart: always