version: '3.7'

services:
  postgres:
    container_name: postgres_subscription
    image: postgres:14.6-alpine
    environment:
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT:-5432}:${DB_PORT}'
    volumes:
      - postgres_subscription:/var/lib/postgresql/data
    command: '-p ${DB_PORT}'

  redis:
    container_name: redis_subscription
    image: redis:latest
    command: '--port ${REDIS_PORT}'
    ports:
      - '${REDIS_PORT:-6379}:${REDIS_PORT:-6379}'
    volumes:
      - redis_subscription:/data

  subscription:
    container_name: subscription_microservice
    build:
      context: .
      dockerfile: Dockerfile
      target: subscription
      args:
        - NODE_VERSION=${NODE_VERSION}
        - MICROSERVICE_PORT=${BOT_APPLICATION_PORT}
    ports:
      - '${SUBSCRIPTION_MICROSERVICE_PORT:-5000}:${SUBSCRIPTION_MICROSERVICE_PORT:-5000}'
    restart: always
    depends_on:
      - postgres

  bot:
    container_name: backend_openai
    build:
      context: .
      dockerfile: Dockerfile
      target: bot
      args:
        - NODE_VERSION=${NODE_VERSION}
        - APP_PORT=${BOT_APPLICATION_PORT}
    ports:
      - '${BOT_APPLICATION_PORT:-3000}:3000'
    restart: always
    depends_on:
      - subscription
      - redis
      - postgres

volumes:
  postgres_subscription:
  redis_subscription:

