version: '3'

services:
  postgres_openai:
    container_name: postgres_openai
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - pg_telegram_openai:/var/lib/postgresql/data

  redis:
    container_name: redis_openai
    image: redis:latest
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_openai:/data

  backend:
    container_name: backend_openai
    build:
      context: .
    ports:
      - '${APPLICATION_PORT:-3000}:3000'
    volumes:
      - type: bind
        source: ./temp
        target: /usr/src/static
    depends_on:
      - postgres_openai
      - redis
    restart: always

volumes:
  pg_telegram_openai:
  redis_openai: